### ISSUE TITLE
Trait 'TCG\Voyager\Traits\HasRelationships' not found

### ISSUE THREAD

**Issue by steveadamsfixedit** [pvtl/voyager-portfolio#2]
On install into Laravel 5.7, with Voyager 1.1:

Seeding data into the database
PHP Fatal error:  Trait 'TCG\Voyager\Traits\HasRelationships' not found in vendor/pvtl/voyager-portfolio/src/PortfolioCategories.php on line 11

**Comment by Liam-PVTL** [comment]
Fixed in 0.2.2. Thank you for your bug report.
