### ISSUE TITLE
Not able to install with voyager-frontend^0.9.1

### ISSUE THREAD

**Issue by ankitchauhan22** [pvtl/voyager-portfolio#3]
Environement Info:
OS: Windows 10
PHP: 7.2

c:\wamp\www\laraapp>composer require pvtl/voyager-portfolio
Using version ^0.2.0 for pvtl/voyager-portfolio
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for pvtl/voyager-portfolio ^0.2.0 -> satisfiable by pvtl/voyager-portfolio[0.2.0].
    - pvtl/voyager-portfolio 0.2.0 requires pvtl/voyager-frontend ~0.8.0 -> satisfiable by pvtl/voyager-frontend[0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.

**Comment by Liam-PVTL** [comment]
Resolved in 0.2.1. Thank you for your bug report.
