### ISSUE TITLE
 laravel/framework v6.0.0

### ISSUE THREAD

**Issue by fhferreira** [pvtl/voyager-portfolio#4]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for pvtl/voyager-portfolio ^0.2.0 -> satisfiable by pvtl/voyager-portfolio[0.2.0].
    - Conclusion: remove laravel/framework v6.0.0

**Comment by Liam-PVTL** [comment]
Resolved in 0.2.1. Thank you for your bug report.
